name: Structural design jobs
favicon: null
layout_spectrum: 0.9853616240434349
typography_spectrum: 0.3666013153269887
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.017805802868679166
  lightness: 0.21083613554947078
  saturation: 0.5141401661094278
  rhythmicContrast: 0.7496655443683267
purpose: []
